service: pizzaApp

provider:
  name: aws
  runtime: nodejs20.x

functions:
  newOrder:
    handler: handler.newOrder
    events:
      - httpApi:
          path: /order
          method: post
  
  getOrder:
    handler: handler.getOrder
    events:
      - httpApi:
           path: /order/{id}
           method: get